"""
init_command.py
---------------
tselect init — interactively generates tselect.yaml for any repo.

Design:
  - Scans repo, finds candidate source and test directories
  - Shows file counts so user can make an informed choice
  - User picks by number — no typing paths
  - Writes tselect.yaml to repo root
  - Works for any Python repo on first run
"""

from pathlib import Path
from collections import defaultdict


IGNORE_DIRS = {
    ".git", "__pycache__", ".venv", "node_modules",
    "build", "dist", ".tox", ".eggs", ".mypy_cache",
    ".pytest_cache", ".ruff_cache", ".graph",
    # vendor / submodule dirs — never the repo's own code
    "third_party", "vendor", "extern", "external",
    "submodules", "deps", "dependencies",
}

LANG_EXT_MAP = {
    ".py":   "python",
    ".java": "java",
    ".js":   "javascript",
    ".ts":   "typescript",
    ".go":   "go",
    ".cpp":  "cpp",
}

TEST_DIR_NAMES = {"test", "tests", "__tests__", "spec"}


def _should_ignore(path: Path) -> bool:
    return any(p in IGNORE_DIRS for p in path.parts)


def _detect_language(repo_root: Path) -> str:
    from collections import Counter
    counter = Counter()
    for path in repo_root.rglob("*"):
        if _should_ignore(path):
            continue
        if path.is_file() and path.suffix in LANG_EXT_MAP:
            counter[LANG_EXT_MAP[path.suffix]] += 1
    if not counter:
        return "python"
    if "python" in counter:
        return "python"
    return counter.most_common(1)[0][0]


def _find_candidate_dirs(repo_root: Path, language: str) -> tuple[list, list]:
    """
    Walk repo and count source/test files per subdirectory.
    Returns sorted lists of (dir, file_count) for source and test dirs.
    """
    source_counts = defaultdict(int)
    test_counts   = defaultdict(int)

    ext_map = {e for e, l in LANG_EXT_MAP.items() if l == language}

    for path in repo_root.rglob("*"):
        if _should_ignore(path):
            continue
        if not path.is_file():
            continue
        if path.suffix not in ext_map:
            continue

        # is this a test file?
        is_test = (
            any(part.lower() in TEST_DIR_NAMES for part in path.parts) or
            path.name.startswith("test_") or
            path.name.endswith("_test.py")
        )

        # count under immediate subdirectory of repo root
        try:
            rel = path.relative_to(repo_root)
            # use depth-2 key: e.g. "torch/_inductor" or "test/inductor"
            parts = rel.parts
            if len(parts) >= 2:
                key = str(Path(parts[0]) / parts[1])
            else:
                key = parts[0]

            if is_test:
                test_counts[key] += 1
            else:
                source_counts[key] += 1
        except ValueError:
            continue

    # sort by file count descending
    source_dirs = sorted(source_counts.items(), key=lambda x: x[1], reverse=True)
    test_dirs   = sorted(test_counts.items(),   key=lambda x: x[1], reverse=True)

    return source_dirs, test_dirs


def _prompt_dirs(label: str, candidates: list, max_show: int = 10) -> list:
    """
    Show numbered list, let user pick one or more by number.
    Returns list of selected dir strings.
    """
    print(f"\n  Candidate {label} directories (by file count):")
    print()

    shown = candidates[:max_show]
    for i, (d, count) in enumerate(shown, 1):
        print(f"    {i:2d}.  {d:<45}  ({count} files)")

    if len(candidates) > max_show:
        print(f"    ... and {len(candidates) - max_show} more")

    print()
    print(f"  Enter numbers to select (e.g. 1,2  or just 1):")
    print(f"  Press Enter to accept top suggestion ({shown[0][0]})")
    print()

    while True:
        try:
            raw = input("  > ").strip()
        except (EOFError, KeyboardInterrupt):
            raw = ""

        if not raw:
            # default: pick the top one
            return [shown[0][0]]

        try:
            indices = [int(x.strip()) for x in raw.split(",")]
            selected = []
            for idx in indices:
                if 1 <= idx <= len(shown):
                    selected.append(shown[idx - 1][0])
                else:
                    print(f"  ⚠️  {idx} is out of range, ignoring")

            if selected:
                return selected
            else:
                print("  No valid selection, try again.")

        except ValueError:
            print("  Please enter numbers like: 1  or  1,2,3")


def _write_yaml(repo_root: Path, language: str, source_dirs: list, test_dirs: list):
    config_path = repo_root / "tselect.yaml"

    src_lines  = "\n".join(f"    - {d}" for d in source_dirs)
    test_lines = "\n".join(f"    - {d}" for d in test_dirs)

    content = f"""# tselect.yaml — generated by 'tselect init'
# Commit this file to your repo.

repo:
  language: {language}
  source_dirs:
{src_lines}
  test_dirs:
{test_lines}

graph:
  rebuild_after_days: 7
  collect_batch_size: 50

runner:
  extra_args: []
  ignore_changed_patterns:
    - "*.json"
    - "*.yaml"
    - "*.yml"
    - "*.csv"
    - "*.db"
    - "*.md"
    - "*.txt"
    - "*.lock"
    - "*.toml"
    - "*.cfg"
    - "*.ini"
    - "*.png"
    - "*.jpg"

ci:
  post_pr_comment: false
  artifact_storage: none
  fail_on_test_failure: true

ml:
  enabled: false
"""
    config_path.write_text(content)
    return config_path


def run_init(repo_root: Path):
    """
    Main entry point for `tselect init`.
    """
    config_path = repo_root / "tselect.yaml"

    print()
    print("=" * 60)
    print("  tselect init — Configure this repo")
    print("=" * 60)

    if config_path.exists():
        print(f"\n  tselect.yaml already exists at {config_path}")
        try:
            overwrite = input("  Overwrite it? (y/N): ").strip().lower()
        except (EOFError, KeyboardInterrupt):
            overwrite = "n"
        if overwrite != "y":
            print("  Aborted. Existing tselect.yaml unchanged.")
            return

    print()
    print("  Scanning repo to find source and test directories...")
    print("  (This may take a few seconds on large repos)")

    language = _detect_language(repo_root)
    print(f"\n  Detected language: {language}")

    if language not in {"python", "java", "javascript", "typescript", "go"}:
        print(f"\n  ⚠️  Language '{language}' is not fully supported yet.")
        print(f"     Supported: python")
        print(f"     Coming soon: java, javascript, typescript, go")
        print(f"     tselect.yaml will be created but graph build may not work.")

    source_candidates, test_candidates = _find_candidate_dirs(repo_root, language)

    if not source_candidates:
        print("\n  ❌ Could not find any source files. Is this the right directory?")
        return

    if not test_candidates:
        print("\n  ❌ Could not find any test files.")
        print("     Make sure your test files follow naming conventions:")
        print("       Python: test_*.py or *_test.py")
        print("       Java:   *Test.java")
        return

    # ── interactive selection ──
    source_dirs = _prompt_dirs("SOURCE", source_candidates)
    test_dirs   = _prompt_dirs("TEST",   test_candidates)

    # ── confirm ──
    print()
    print("  ─" * 30)
    print(f"  language    : {language}")
    print(f"  source_dirs : {source_dirs}")
    print(f"  test_dirs   : {test_dirs}")
    print("  ─" * 30)
    print()

    try:
        confirm = input("  Write tselect.yaml with these settings? (Y/n): ").strip().lower()
    except (EOFError, KeyboardInterrupt):
        confirm = "y"

    if confirm in {"", "y"}:
        path = _write_yaml(repo_root, language, source_dirs, test_dirs)
        print(f"\n  ✅ tselect.yaml written to: {path}")
        print()
        print("  Next steps:")
        print("    tselect build-graph   # build dependency graph")
        print("    tselect run           # select tests for changed files")
    else:
        print("  Aborted. No file written.")